### ISSUE TITLE
Add erode() function to GridObject

### ISSUE THREAD

**Issue by Teschl** [TopoToolbox/pytopotoolbox#105]
As mentioned in https://github.com/TopoToolbox/libtopotoolbox/issues/103#issuecomment-2522617594

**Comment by Teschl** [comment]
I will implement this now.

**Comment by Teschl** [comment]
@wkearn We might have to implement our own version of `imerode()`, since I have not been able to find a function that replicates the Matlab `imerode` function. There are (binary) erosion functions like [`scipy.ndimage.binary_erosion`,](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.binary_erosion.html) [`skimage.morphology.erosion`](https://scikit-image.org/docs/stable/api/skimage.morphology.html#skimage.morphology.erosion) and [`cv.erode`](https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html#gaeb1e0c1033e3f6b891a25d0511362aeb). However, I was not able to replicate the Matlab [`imerode`](https://de.mathworks.com/help/images/ref/imerode.html) example. Also, I am not sure howmany dependencies we want to add apart from scipy.

Is the Matlab function only used for binary erosion? How shuld we handle this?

**Comment by wkearn** [comment]
Check out 
[scipy.ndimage.grey_erosion](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.grey_erosion.html). 
Since the typical DEM is continuously valued, we need to use greyscale 
erosion rather than binary erosion.
