### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Teschl** [TopoToolbox/pytopotoolbox#18]
Some needed improvements:

- [x] Better explain how to build the package from the repository, especially going into more detail for installing on Windows
- [x] Remove outdated information
- [x] Include a short explanation on where to find the examples and what to do with them
- [x] adding badges
- [ ] how to run tests (needs tests to be added #9 )

This list is not complete at all, just to get the README.md up to date.

**Comment by wkearn** [comment]
See #25, which updated the installation guide. 

I also added some checkboxes to keep track of the other tasks.
