### ISSUE TITLE
Add excesstopography function

### ISSUE THREAD

**Issue by Teschl** [TopoToolbox/pytopotoolbox#42]

**Comment by Teschl** [comment]
@wkearn We have two options on how to implement this:

1. provide excesstopography() with the option to change method
    like so for example: `excesstopography(method='fsm2d')`
3. provide excesstopography_fsm2d, excesstopography_fmm2d and excesstopography_fmm3d separately

I think both are valid options, but I would prefer 1 if one of the algorithms is used more commonly than the others.

**Comment by Teschl** [comment]
Ok, sounds good. Option one with `fsm2d` as default it is. 

Regarding the `threshold_slopes`, how will this be provided? Right now, I have just been using a matrix that is filled with one value (like 0.2). Do we expect the user to provide a matrix?

I was thinking something like this:

1. `excesstopography(0.2)` where the `threshold_slopes` will be filled with 0.2
2. `excesstopography(some_matrix)` where the `threshold_slopes` is my_matrix
3. `excesstopography()` where a default `threshold_slope` will be used
4. all of the above

For option 2 we might have to implement an easy way to generate the required matrix.

**Comment by wkearn** [comment]
I think all of the above options are reasonable to provide if that's possible. Another option is that you have a `GridObject` that contains the `threshold_slopes`. This would be similar to option 2, but it might be nicer to call `dem.excesstopography(thresholds)` than to have to remember to call `dem.excesstopography(thresholds.z)` in that case.
