### ISSUE TITLE
Row/column major problem with fillsinks

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/pytopotoolbox#50]
While looking at #48, I noticed that `fillsinks` seems to give the wrong answer when you pass it a DEM that isn't square:

```python
import topotoolbox as topo
import matplotlib.pyplot as plt
import numpy as np

dem = topo.load_dem("tibet");
filled = dem.fillsinks();

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12,4))
ax1.imshow(dem,cmap='terrain')
ax1.set_title('original')
ax2.imshow(filled,cmap='terrain')
ax2.set_title('filled')
plt.show()
```
![filled_dem](https://github.com/user-attachments/assets/fb35d802-fb23-47b9-ba75-d430993657a4)

This looks like we're passing the row-major Numpy array to libtopotoolbox in the wrong order. If I swap the rows and columns arguments to `grid_fillsinks`, I get something more like what I would expect:

```python
output = np.zeros_like(dem.z)
topo._grid.grid_fillsinks(output,dem.z,dem.columns,dem.rows)
plt.imshow(output,cmap='terrain')
```
![expected](https://github.com/user-attachments/assets/9766ba96-f75b-4f2e-a2fb-2374c9fcde46)

I investigated a little bit, and I think this may not have worked properly since we added the pybind11 interface to `fillsinks`. I remember swapping the array order when we were using `ctypes` (https://github.com/TopoToolbox/pytopotoolbox/pull/8#discussion_r1555717678), but it looks like we didn't copy that behavior properly when we added the `fillsinks` binding in #14. 

I am a little confused because I could have sworn I had looked at the output of `fillsinks` since we merged #14. Have you noticed this recently, @Teschl? I do want to make sure that this hasn't arisen because of a more recent change or something that changed in libtopotoolbox.

In any case, this should be an easy fix: swap the order of `dem.columns` and `dem.rows` when you pass them to `grid_fillsinks`. It would be nice to have a test (#41) that captures this in case it breaks again in the future -- I am thinking ahead to TopoToolbox/libtopotoolbox#68, in particular.

We also need to change this behavior in `identifyflats`, which seems like it should have the same problem.

**Comment by Teschl** [comment]
That's interesting, I have never observed this before. I could have sworn that I ran fillsinks with 'taiwan' before and that did not have those artefacts. It's also not square, but tall instead of wide, if that makes sense.
When I try to run 'taiwan' fillsinks doesn't even work any more. Could this be because I haven't set the hardcoded release?

**Comment by Teschl** [comment]
I have tested it with the 2024-W27 release, that also doesn't work, so I think it's safe to assume that the issue got nothing to do with the libtopotoolbox implementation.

**Comment by wkearn** [comment]
Taiwan doesn't run because it has NaNs (TopoToolbox/libtopotoolbox#20). If you fill the NaNs with 0, then it should run to completion.

**Comment by Teschl** [comment]
Ah you are right. Interesting that to see that they get different kinds of artifacts:
![image](https://github.com/user-attachments/assets/914bfb12-c035-4be9-8170-2500a45e0da1)

**Comment by bgailleton** [comment]
Hi @wkearn and @Teschl,
I am facing the same with my own tif files and I can confirm this is due to the index in libtopotoolbox being column major while the DEM is stored as row major (I think most DEMs are encoded that way by default?).

**Comment by bgailleton** [comment]
There is probably a much cleaner way to do so but I am using this quick fix at loading to get the array compatible:
```
dem.z = np.flip(np.rot90(dem.z.flatten(order='F').reshape(dem.columns,dem.rows)),0)
```

**Comment by Teschl** [comment]
Hi @bgailleton,
that was also the solution I came up with (just without the flipping), so thanks for confirming that this seems to be the right approach.
When we still used ctypes, this was solved by using the `F_CONTIGUOUS` flag when calling the C function. That removed the need to handle this inside the ndarray's.
