### ISSUE TITLE
Magic functions in FlowObject

### ISSUE THREAD

**Issue by Teschl** [TopoToolbox/pytopotoolbox#64]
In the GridObject there is only one attribute that is an array/matrix. In the FlowObject there are at least target, source and direction arrays. I think maybe that should also include the filled_dem, but that is not the issue here.

How should the FlowObject behave when something like this happens: `result = flow_obj1 and flow_obj2` which of the arrays should be compared? My assumption would have been to just do all, but the result could be of a different datatype than the original array. That would break using it with other functions later. Which should get used when plotting? 

This also extends back to the GridObject. Should we force the array to be one datatype, or are we ok with having GridObjects that are int or float? All this could result in weird and hard to understand behavior. I can't think of a straight forward solution to all this as of right now.

**Comment by wkearn** [comment]
The MATLAB `FLOWobj` does not have the same overloaded operators that `GRIDobj` for the reason that you identified: it doesn't make so much sense to combine multiple FLOWobj. So my instinct would be to not provide the magic functions for `FlowObject`. It really shouldn't be possible to do arithmetic or logical comparisons on `FlowObject`.

Likewise there isn't a default plotting method provided for `FLOWobj`, so we may not need to provide one here.

For the `GridObject` magic functions, I would treat two `GridObject`s as 2D NumPy arrays and just do whatever happens to the types when you add/subtract/and/or/whatever two NumPy arrays together. I think it is reasonable to allow users to create a `GridObject` with whatever data type is appropriate for them. We just need to make sure that we convert things to the appropriate types when they are passed to libtopotoolbox functions.

**Comment by wkearn** [comment]
Do we still need to do anything here? I think we don't need the magic functions for `FlowObject`, but did you want to make some updates to the `GridObject` ones to make them behave more consistently or has that been taken care of?

**Comment by Teschl** [comment]
I don't think this is relevant anymore.  I think the `GridObject` magic functions are fine where they are now.
