### ISSUE TITLE
Supply boundary conditions to `fillsinks` and handle NaNs properly

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/pytopotoolbox#69]
TopoToolbox/libtopotoolbox#135 changed the API for `fillsinks` and `fillsinks_hybrid` to include a `bc` argument:

```C
void fillsinks(float *output, float *dem, uint8_t *bc, ptrdiff_t dims[2]);
void fillsinks_hybrid(float *output, ptrdiff_t *queue, float *dem, uint8_t *bc, ptrdiff_t dims[2]);
```

`bc` is a pointer to a `uint8_t` array of the same shape as the DEM and other arrays. It takes a value of 1 on pixels that should be fixed to their values in the DEM and 0 for pixels that should be filled. Normally, we would pass an array that has 1 on the edges and 0 on the interior.

We can also use the `bc` array to deal with NaNs. To replicate the behavior of TopoToolbox v2, which should probably be the default for pytopotoolbox, we need to do the following:

1. Find all the NaNs in the DEM: `N = np.isnan(DEM)`.
2. Set the NaNs in the DEM to negative infinity (`DEM[N] = -np.inf`).
3. Set the `bc` array to have 1 on the border /and for any pixels that were originally NaNs in the DEM/ and 0 for all other pixels.
4. Run `fillsinks` or `fillsinks_hybrid` as before, but pass the pointer to the `bc` data.
5. Once we are done, restore the NaN pixels in both the original and filled DEMs (they will equal `-np.inf` otherwise). This does require some care around copying vs. in-place modification of the original DEM.

@Teschl: Let me know if you would like to work on this. I'm happy to implement it if you'd rather deal with other things.

TopoToolbox/libtopotoolbox#135 should land in the 2024-W43 release of libtopotoolbox next Monday.

**Comment by Teschl** [comment]
If you want, feel free to implement it yourself. Should we also add a separate python `fillsinks_hybrit()` function? If so, I could implement the both changes in the same pull request.

Otherwise, I will get back to the `acv()` function (topotoolbox/libtopotoolbox#100).

**Comment by wkearn** [comment]
I will take care of this then and you can keep working on `acv`. 

The distinction between `fillsinks` and `fillsinks_hybrid` should not be that relevant to most users, since it is mostly a memory vs. performance tradeoff. I think we should probably implement it as an option that users can switch between when they call `GridObject.fillsinks`, and do some testing to figure out which usually performs best on real DEMs -- it should theoretically be `fillsinks_hybrid`, but I'm not so sure of how it works out in practice. I can implement the `fillsinks_hybrid` dispatch as well.
