### ISSUE TITLE
Rework URLs for docs

### ISSUE THREAD

**Issue by Teschl** [TopoToolbox/pytopotoolbox#81]
The way the docs generation is set up right now, the example notebooks are accessed with the following URL `https://topotoolbox.github.io/pytopotoolbox/_temp/`, meaning they get saved in `_temp/` which is not really a logical name when looking at the URL. I propose this should be changed to something along the lines of `examples/`

**Comment by wkearn** [comment]
Would it make sense to move the `examples/` directory from the root of the repository to the `docs/` directory? I think it is all right if they are kept in there, as long as we change the link in the README.
