### ISSUE TITLE
Provide example data for testing and documentation

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/pytopotoolbox#9]
The example datasets are valuable to have around for testing and documentation, but we should generally avoid committing large binary files to the repository if we can. I think we need a system where we can store example data files outside the repository and download them either when the package is installed or when the user tries to access them.

**Comment by Teschl** [comment]
I was thinking we could handle example datasets like seaborn. [load_dataset()](https://seaborn.pydata.org/generated/seaborn.load_dataset.html) will load an example dataset from the online repository.

> This function provides quick access to a small number of example datasets that are useful for documenting seaborn or generating reproducible examples for bug reports. It is not necessary for normal usage.

Using the [example DEMs](https://github.com/wschwanghart/DEMs) we could add functions equivalent to: `seaborn.load_dataset()` and `seaborn.get_dataset_names()`. We still should keep the random generation, so one can observe changes on a smaller, more visible scale. 
I'll work on getting a pull request ready for this.
